# Generated by Django 4.1.5 on 2023-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_city_scrap_address_rename_pin_scrap_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
