# Generated by Django 4.1.5 on 2023-01-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_scrap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='vendorId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrap',
            name='vendorName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
