# Generated by Django 4.1.5 on 2023-01-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_scrap_vendorid_scrap_vendorname'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='PickUpDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
