# Generated by Django 4.1.5 on 2023-01-26 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0002_vendorprofile_delete_profileslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='Vendor_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
