# Generated by Django 4.1.5 on 2023-01-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_vendorprofile_vendor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='Address',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='City',
            new_name='District',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='Email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='First_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='GST_No',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='License_No',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='Postcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='Surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
